(executables
 (names instrumentation scenario_fuzz)
 (modules instrumentation scenario_fuzz)
 (libraries harness crowbar)
 (modes exe))

(executable
 (name core_fuzz)
 (modules core_fuzz)
 (libraries http-kit-core crowbar)
 (modes exe))

(executable
 (name http1_fuzz)
 (modules http1_fuzz)
 (libraries http-kit-core http-kit-http1 crowbar)
 (modes exe))
